
name: CI-DEV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup hardhat environment
        run: npm install

      - name: Create .env
        uses: weyheyhey/create-dotenv-action@v1
        with:
          wildecard: "^"
        env:
          ^MUMBAI_URL: ${{ secrets.MUMBAI_URL }}
          ^PRIV_KEY0: ${{ secrets.PRIV_KEY0 }}
          ^PRIV_KEY1: ${{ secrets.PRIV_KEY1 }}
          ^PRIV_KEY2: ${{ secrets.PRIV_KEY2 }}

      - name: deploy contracts
        run: npx hardhat run scripts/deploy.ts --network mumbai

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://npm.pkg.github.com
          package: deployed/package.json
